### ISSUE TITLE
ULongTest.java is locale-dependent

### ISSUE THREAD

**Issue by mreithub** [trejkaz/hex-components#15]
`ULongTest.java` depends on local number format.

On my system, `ULong.toString()` produces `9.223.372.036.854.775.808` instead of `9,223,372,036,854,775,808`.

Exception:

    testToString(org.trypticon.hex.interpreters.primitives.unsigned.ULongTest)  Time elapsed: 0.012sec  <<< FAILURE!
    org.junit.ComparisonFailure: Wrong string value expected:<9[,223,372,036,854,775,]808> but was:<9[.223.372.036.854.775.]808>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.trypticon.hex.interpreters.primitives.unsigned.ULongTest.testToString(ULongTest.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    --snip--

Some information on my system (debian jessie amd64):
 
    $ java -version
    java version "1.8.0_25"
    Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

    $ locale
    LANG=de_AT.UTF-8
    LANGUAGE=
    LC_CTYPE="de_AT.UTF-8"
    LC_NUMERIC="de_AT.UTF-8"
    LC_TIME="de_AT.UTF-8"
    LC_COLLATE="de_AT.UTF-8"
    LC_MONETARY="de_AT.UTF-8"
    LC_MESSAGES="de_AT.UTF-8"
    LC_PAPER="de_AT.UTF-8"
    LC_NAME="de_AT.UTF-8"
    LC_ADDRESS="de_AT.UTF-8"
    LC_TELEPHONE="de_AT.UTF-8"
    LC_MEASUREMENT="de_AT.UTF-8"
    LC_IDENTIFICATION="de_AT.UTF-8"
    LC_ALL=

My workaround for this issue for now is to add a `.replace('.', ',')` after the `.toString()` but that assumes that there are no other possible formats.

**Comment by trejkaz** [comment]
I think that in this case the behaviour of ULong is right (for all types, toString() currently formats using the default locale), so yeah, the test is wrong. I'll just have to have the test explicitly format it using Locale.ROOT to get it to pass more consistently when run on a different locale.

**Comment by mreithub** [comment]
Thanks for responding that quickly.
I took the liberty of fixing this (and some other issues I stumbled onto) myself and created a merge request for both this and your `hex` project.

**Comment by trejkaz** [comment]
Fixed by pull request #16
